name: Check Solution

on:
  # Triggers the workflow on push or pull request events
  pull_request:

jobs:
  compile_and_run_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
          java-package: jdk
      - name: Compile solution
        # before running tests, try to compile the solution
        run: ./gradlew compileTestJava --continue --info
      - name: Run Gradle tests
        # we want gradle to do as much as possible, and show info about failing tests
        run: ./gradlew check --continue --info
        # we want to publish report even if tests are failing
        continue-on-error: true
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          check_name: Public Tests Report
          report_paths: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_failure: true
